FROM node:14.4.0-alpine

WORKDIR /app

ENV PATH $PATH:app/node_modules/.bin

RUN apk update \
    && apk add --no-cache \
    bash \
    musl-dev

COPY ./package.json app/package.json

RUN npm install --no-optional && npm cache clean --force

COPY ./entrypoint.sh .

RUN chmod 700 entrypoint.sh

COPY . .

ENTRYPOINT ["/app/entrypoint.sh"]