"""empty message

Revision ID: 2c77e244037d
Revises: 
Create Date: 2021-10-06 16:33:44.370726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c77e244037d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('INACTIVE', 'STANDARD', 'SUPERVISOR', 'MANAGER', 'ADMIN', name='access'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('ballance', sa.Float(), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sub_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ballance', sa.Float(), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.Column('main_account', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_account'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'member_id'),
    sa.UniqueConstraint('team_id', 'member_id', name='team_assignment')
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('sub_account', sa.Integer(), nullable=True),
    sa.Column('ammount', sa.Float(), nullable=False),
    sa.Column('ballance', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sub_account'], ['sub_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assigner', sa.Integer(), nullable=False),
    sa.Column('allocation', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'VIEWED', 'INPROGRESS', 'ONHOLD', 'SUBMITED', 'REJECTED', 'VERIFIED', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allocation'], ['allocations.id'], ),
    sa.ForeignKeyConstraint(['assigner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('end_status', sa.Enum('CREATED', 'ASSIGNED', 'VIEWED', 'INPROGRESS', 'ONHOLD', 'SUBMITED', 'REJECTED', 'VERIFIED', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('recept', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image'], ['images.id'], ),
    sa.ForeignKeyConstraint(['task'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_notes')
    op.drop_table('tasks')
    op.drop_table('allocations')
    op.drop_table('team_members')
    op.drop_table('sub_accounts')
    op.drop_table('teams')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('images')
    # ### end Alembic commands ###
