"""empty message

Revision ID: 832a1fd6237b
Revises: 2c77e244037d
Create Date: 2021-10-06 16:35:02.446733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832a1fd6237b'
down_revision = '2c77e244037d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('team_assignment', 'team_members', ['team_id', 'member_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_assignment', 'team_members', type_='unique')
    # ### end Alembic commands ###
