# pull official base image
FROM python:3.8.0-alpine

# set work directory
WORKDIR /usr/src/app

# install psycopg2 dependencies
RUN apk update \
    && apk add \
    bash\
    g++ \
    gcc \
    musl-dev \
    postgresql-dev \
    python3-dev
    
#install operating dependencies
RUN apk update \
    && apk add --no-cache \
    bash 

# install python packages
RUN pip install --upgrade pip \
    && pip install --upgrade wheel
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN apk add build-base
RUN pip install -r requirements.txt
RUN pip install coverage

#copy entrypoint.sh
COPY ./entrypointtest.sh /usr/src/app/entrypointtest.sh

#setting file permissions
RUN chmod 700 /usr/src/app/entrypointtest.sh

# copy project
COPY . /usr/src/app/

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypointtest.sh"]