"""empty message

Revision ID: bb2a9f949abc
Revises: 15d4ad219098
Create Date: 2021-10-03 16:56:08.158573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2a9f949abc'
down_revision = '15d4ad219098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('assignment', 'team_members', ['team_id', 'member_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignment', 'team_members', type_='unique')
    # ### end Alembic commands ###
